### ISSUE TITLE
gxuiでほしい機能

### ISSUE THREAD

**Issue by kyokomi** [kyokomi/gxjan#3]
- [ ] layer定義を別ファイルにしたい（xml・・・・？）
- [ ] AddChildする要素に名前をつけてSearchしたい

**Comment by ben-clayton** [comment]
Hi @kyokomi,
I'm happy to see you're able to build something functional with GXUI. If you have feature requests, feel free to raise these on the [GXUI project](https://github.com/google/gxui/issues).

Regards,
Ben

**Comment by kyokomi** [comment]
Hi @ben-clayton

Thank you!
